# Generated by Django 6.0.2 on 2026-06-08 05:17

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='embed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='coverArt',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, quality=100, scale=1, size=[3000, 3000], upload_to='music/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
